#!/usr/bin/env bash
# Available from https://gist.github.com/pfaffman/8644399

if [ $# -lt 1 ]
then
    echo "Usage " $0 files
    echo "   Replaces names (or any words) in files passed on the command line."
    echo "   Edit below to change what names get replaced."
    exit
fi

# The "\<" and "\>" characters around OLDNAME below tells the sed
# command that replacement work only for whole words. For example, if
# you are replacing "Bill" with "Joe," you do not want to replace
# "Billing" with "Joeing".

# For each first and last name, duplicate the sed line below to replace in all
# of the documents passed on the command line.
# For example, this next line will perform these replacements on all .txt files:
#   ./fixNames *.txt

for file in $*
do
    echo -n "Processing " $file ". . . "
    # Stick in as many names like these as you need to
    # OLDNAME will be replaced with NEWNAME in each file passed to this script
    sed --in-place -e 's/\<OLDNAME\>/NEWNAME/g' $file
    sed --in-place -e 's/\<John\>/James/g' $file
    sed --in-place -e 's/\<Dewey\>/Jones/g' $file
# Use lines like this next one if you use Mac OS X
#    sed --in-place -e 's/[[:<:]]OLDNAME[[:>:]]/NEWNAME/g' $file
    echo done.
done
exit

